### ISSUE TITLE
Seems to be broken out of the box

### ISSUE THREAD

**Issue by ghost** [opf/openproject-docker-compose#1]
![docker-ps](https://user-images.githubusercontent.com/2616473/102542369-99c76680-4116-11eb-9b6b-7c1ae2c9f988.PNG)

![errors](https://user-images.githubusercontent.com/2616473/102542383-9d5aed80-4116-11eb-93d3-bcd7be9710df.PNG)

**Comment by redge76** [comment]
Same here. I just tried and I get the same results
![image](https://user-images.githubusercontent.com/1172508/102544109-9d2a0600-40b4-11eb-8164-9c3e08e4d6ad.png)

**Comment by redge76** [comment]
It seems that the version 11.1 does not work with this docker-compose.
Just edit the docker-compose.yml and force it to use the old version with:
x-op-image: &image
  image: openproject/community:11.0

**Comment by notder** [comment]
I found out that there are executable file in `/app/docker/prod/` on docker image `openproject/community:11`
So you'll need to add /prod/ in `compose/docker-compose.yml`


```
command: "./docker/prod/proxy"
command: "./docker/prod/web"
command: "./docker/prod/worker"
command: "./docker/prod/cron"
command: "./docker/prod/seeder"
```

**Comment by machisuji** [comment]
Sorry, that was simply a wrong path as @notder pointed out. It's fixed now.
