### ISSUE TITLE
seeder service have two restart policies

### ISSUE THREAD

**Issue by jakegrabowski** [opf/openproject-docker-compose#11]
Noticed that seeder have set two policies "unless-stopped" and "on-failure". Is this intendent?

**Comment by b12f** [comment]
Hi @jakegrabowski afaik, the latter overwrites the former, which means that only the `on-failure` restart policy is set on this particular container.

If you start the stack and inspect it you can see this;

```
$ docker-compose up -d
$ docker inspect compose_seeder_1
[..]
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 0
            },
[..]
``

**Comment by jakegrabowski** [comment]
I know but that was different from pattern that emerged from whole compose file so I wanted to ask if this is intendent and apparently it is - Thanks
