### ISSUE TITLE
Postgres version upgrade v10 => v13

### ISSUE THREAD

**Issue by jthomaschewski** [opf/openproject-docker-compose#13]
The example `docker-compose.yml` still references a postgres v10 image: https://github.com/opf/openproject-deploy/blob/stable/12/compose/docker-compose.yml#L33
Is this intentional or WIP?

The compose upgrade guide doesn't mention anything right now as well:
https://www.openproject.org/docs/installation-and-operations/misc/migration-to-postgresql13/#compose-based-docker-installation

Is docker-compose still a supported installation method?

**Comment by machisuji** [comment]
Thank you @jthomaschewski. I've updated the `docker-compose.yml`.

Docker-compose is certainly still supported. There are upgrade instructions for pg13 in this very repository.
I have updated the [docs](https://github.com/opf/openproject/commit/bbb59ac5a074083e5c193cdf411657498dd3db02) accordingly. They will appear on the website with the next update.

**Comment by machisuji** [comment]
Closing this issue.
