### ISSUE TITLE
Problem With New Health Check Container in OpenProject 12 Docker Compose Script?

### ISSUE THREAD

**Issue by gohrner** [opf/openproject-docker-compose#14]
As the Docker Compose script was now updated to work with PostgreSQL 13, I immediately tried it out.

Everything seemed to work fine, including DB conversion / upgrade, but afterwards I noticed that in general OpenProject 12 was running, but became inaccessible for a while every few minutes, so working with it was not really possibly.

This seems to be caused by an amok running health check which always marks the web container as "unhealthy" and restartet it every minute or so.

It took me a while to figure out, as I had never encountered such a "heal check" stuff for Docker Containers before.

No sure if I understood the health check correctly, but at least if I run the health check command in the autoheal container - is this the right one to execute it in, or where should I execute it to test? - it always fails, even though the web container seems to be running fine:

```
$ docker container exec -ti openproject_test_12_autoheal_1 sh -l
83230a91fb2d:/# curl -f http://localhost:80/health_checks/default
curl: (7) Failed to connect to localhost port 80 after 0 ms: Connection refused
83230a91fb2d:/# 
```

The same also happens if I try to do it in the Web Container:

```
$ docker container exec -ti openproject_test_12_web_1 sh -l
# curl -f http://localhost:80/health_checks/default
curl: (7) Failed to connect to localhost port 80: Connection refused
# 
```

Note that OpenProject itself is working fine.

I worked around this "amok autohealer" by just commenting out all health check / autoheal additions from the Docker Compose script and recreating the containers.

**Comment by gohrner** [comment]
Addendum: This breakage seems to have been caused by https://github.com/opf/openproject-deploy/commit/44a239ded5a2a290e5e461642751905926c6896a

**Comment by oliverguenther** [comment]
Hi @machisuji , since you implemented the autoheal in https://github.com/opf/openproject-deploy/pull/8, could you take a look at this?

**Comment by machisuji** [comment]
The problem was an [incorrect port](https://github.com/opf/openproject-deploy/commit/687918e72272aaa3e394b777cf8ea90d6699144d) in the health check. Please update your docker-compose.yml to the latest version (and re-create the web and autoheal containers) to fix the issue.

**Comment by gohrner** [comment]
@machisuji : Following commit changes the health check port again from 8080 to 8000 - is this intended?

9a5921d05a957625bdb9d68055a591302b256ad6

**Comment by machisuji** [comment]
@gohrner Thanks you! No, that was me fatfingering the commit. I had changed the port (and the health restart policy) to test something. I thought I reverted those changes before comitting. I should wait until the next morning next time I want to fix something like that. ;)

I've now really fixed.

@oliverguenther Can you please have a look again too to make extra sure everything is correct now? Just a quick checkout and `docker-compose up -d` to see if everything is working for you properly now (i.e. the web container is staying healthy). I've double checked and now it's (really ;)) all good as far as I can tell.
