### ISSUE TITLE
[Docker] Container compose_web_1 found to be unhealthy

### ISSUE THREAD

**Issue by MathieuRS1** [opf/openproject-docker-compose#15]
Hi,

On a fresh install with docker, I got this problem recursively. Any idea ?

 Booting Puma
web_1       | => Rails 6.1.4.1 application starting in production
web_1       | => Run `bin/rails server --help` for more startup options
web_1       | W, [2021-12-19T18:43:21.704559 #1]  WARN -- : Creating scope :open. Overwriting existing method GithubPullRequest.open.
web_1       | [1] Puma starting in cluster mode...
web_1       | [1] * Puma version: 5.5.2 (ruby 2.7.5-p203) ("Zawgyi")
web_1       | [1] *  Min threads: 4
web_1       | [1] *  Max threads: 16
web_1       | [1] *  Environment: production
web_1       | [1] *   Master PID: 1
web_1       | [1] *      Workers: 2
web_1       | [1] *     Restarts: (✔) hot (✖) phased
web_1       | [1] * Preloading application
web_1       | [1] * Listening on http://0.0.0.0:8080
web_1       | [1] Use Ctrl-C to stop
web_1       | [1] - Worker 0 (PID: 36) booted in 0.01s, phase: 0
web_1       | [1] - Worker 1 (PID: 42) booted in 0.0s, phase: 0
autoheal_1  | 19-12-2021 18:44:05 **Container /compose_web_1 (19934500d80e) found to be unhealthy - Restarting container now with 10s timeout**
web_1       | [1] === puma shutdown: 2021-12-19 18:44:05 +0000 ===
web_1       | [1] - Goodbye!
web_1       | [1] - Gracefully shutting down workers...
web_1       | Exiting

**Comment by machisuji** [comment]
Mh there seems to be an issue with the health check. For now the solution would be to comment out the autoheal service and the healthcheck section of the web service. I'll look into it as soon as I can.

**Comment by machisuji** [comment]
This is the same issue as reported in #14 which has been fixed now. Please update your docker-compose.yml to the latest version and re-create the web and autoheal containers.
