### ISSUE TITLE
Error pulling image config: TLS handshake timeout

### ISSUE THREAD

**Issue by bitshiftnetau** [opf/openproject-docker-compose#18]
Having a few issues deploying this to a fresh install with docker. 

I followed the instructions here: https://www.openproject.org/docs/installation-and-operations/installation/docker/

Upon running `docker-compose pull` I get the following error:

`error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/48/487a6b982637737434edc432eb386d7d1d4f15a437275ada6261da640511c722/data?verify=1641586568-0eOijBTP23A2cjIR%2FCfvj92zESQ%3D": net/http: TLS handshake timeout`

**Comment by openpkrump** [comment]
Hi bitshiftnetau, if the issue still persists and you have an enterprise plan, please email us (mailto:support@openproject.com)
