### ISSUE TITLE
k8s install failed with fatal error stable 12

### ISSUE THREAD

**Issue by lspvic** [opf/openproject-docker-compose#29]
ArgumentError: Value for edition must be one of standard, bim but is classic
I think it is related with this commit https://github.com/opf/openproject-deploy/commit/19269f8429084560ddbdedfa500837d97e5e4d5f add the env `OPENPROJECT_EDITION=class`

**Comment by JulianBueno-Code** [comment]
change OPENPROJECT_EDITION to standard

**Comment by wielinde** [comment]
@machisuji That's true. "classic" is the wrong value for normal OpenProject. It needs to be "standard". See allowed values here https://github.com/opf/openproject/blob/d5f00b5700eae4ef06acd6277a5e718f474a40a6/config/constants/settings/definitions.rb#L347

**Comment by machisuji** [comment]
My bad! Fixing it.

**Comment by machisuji** [comment]
This has been fixed. Sorry for the trouble.
