### ISSUE TITLE
How to skip creating the demo projects?

### ISSUE THREAD

**Issue by MaurizioCasciano** [opf/openproject-docker-compose#31]
I have installed OpenProject using the provided docker-compose.yml file and everything is working fine,
however I did not found a way to skip the creation of the default projects:

![Screenshot from 2022-06-10 17-01-16](https://user-images.githubusercontent.com/12021064/173094372-d5a572b6-f96b-4c4a-86f6-eb39c723a2a0.png)

Hoc can I configure it in order to avoid the creation of **Scrum project** and **Demo project**?

**Comment by oliverguenther** [comment]
Hi @MaurizioCasciano , currently the demo projects will always be created. Feel free to add a feature request in our community  https://community.openproject.org/ to make this configurable. The rest of the seeders are necessary as this seeds, for example, the admin user.

Best
Oliver
