### ISSUE TITLE
Postgresql deployment fail to start

### ISSUE THREAD

**Issue by Timizki** [opf/openproject-docker-compose#34]
I tried to install the openproject to the Microsoft Azure AKS kubernetes instance but openproject failed to start because postgresql's data directory was not empty (it contained lost+found directory)

**Affected version**
stable/12

**How to repeat**
Aquire Azure AKS instance
Clone: git clone https://github.com/opf/openproject-deploy --depth=1 --branch=stable/12 openproject
Create new namespace: kubectl create namespace openproject
Install: kubectl apply . -n openproject

**Validate error**
Get pods: kubectl get pods -n openproject
`
NAME                     READY   STATUS             RESTARTS      AGE
cache-d88d87f6d-84l7q    1/1     Running            0             2m18s
cron-7dbc56b55c-4scbg    1/1     Running            0             2m17s
db-6c5c8f9bc9-mgb9m      0/1     CrashLoopBackOff   4 (36s ago)   2m18s
proxy-797b9b5dc6-m6kvf   1/1     Running            0             2m17s
seeder                   0/1     CrashLoopBackOff   3 (31s ago)   2m17s
web-6d4df698b9-29rwl     0/1     CrashLoopBackOff   2 (31s ago)   2m17s
worker-d9bc84777-s692l   1/1     Running            3 (38s ago)   2m17s
`

Get logs of the db pod: kubectl -n openproject logs db-6c5c8f9bc9-mgb9m 
`
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
It contains a lost+found directory, perhaps due to it being a mount point.
Using a mount point directly as the data directory is not recommended.
Create a subdirectory under the mount point.
`

**Comment by oliverguenther** [comment]
K8s deployment has moved to helm chart. I'm closing all remaining issues. In case you need help, please:
- Open an issue: https://github.com/opf/helm-charts/issues/new
- Use the discussions: https://github.com/opf/helm-charts/discussions
