### ISSUE TITLE
Install OpenProject - Portainer

### ISSUE THREAD

**Issue by IkhsanLPK** [opf/openproject-docker-compose#40]
![image](https://user-images.githubusercontent.com/96222687/189115013-0b367267-e8d5-4f5c-8b78-9b8e60a81370.png)
hi,
someone please help me to explain this note, for deploying OpenProject using portainer, i have no idea which brackets to replace this mark "<<"

Thanks!

**Comment by actorius** [comment]
Create stack with this settings:

![image](https://user-images.githubusercontent.com/855531/217961857-7449b077-8829-4eea-a2a2-0819bd05920d.png)
