### ISSUE TITLE
time problem

### ISSUE THREAD

**Issue by onlineyh** [opf/openproject-docker-compose#48]
Hello, when I use openprojcet, I found that the modification time of the administrator is different from that of ordinary users. I am in +8:00 time zone, ordinary users are in utc time, administrators are in +8:00 time, there is a difference of 8 hours in between, how to modify it? I am using docker to deploy openproject, thank you!

**Comment by openpkrump** [comment]
Hi onlineyh, thank you for reaching out to us. Inquiries like these one are handled within our helpdesk system. If you have issues like these and have an enterprise plan, please send us an email to support@openproject.com
