### ISSUE TITLE
Invalid interpolation format

### ISSUE THREAD

**Issue by 4li-ra** [opf/openproject-docker-compose#5]
Hi
I get this error on docker-compose pull:
ERROR: Invalid interpolation format for "environment" option in service "cron": "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"

after some search I changed & to $$ and the error disappered but this new error happened:
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
I use docker compose 1.17.1 & docker  20.10.2

**Comment by cwaidelich** [comment]
I updated docker-compose to 1.29.1 and this issue was solved.
