### ISSUE TITLE
Docker multi-container stops at 11AM and 11PM everyday

### ISSUE THREAD

**Issue by jasgggit** [opf/openproject-docker-compose#51]
Hi, I've deployed the docker installation, using the multi-container method and now the container stack shuts down every 12hrs, at 11 Am and 11 PM.

I can't find any clues for the issue on the logs, and I hope you can shine some light on how to debug this issue.

Regards and thanks in advance for the help.

JG

**Comment by b12f** [comment]
If the whole stack is doing so that reads like you have something going on on the host. Perhaps a cronjob that restarts the docker daemon?

**Comment by jasgggit** [comment]
> If the whole stack is doing so that reads like you have something going on on the host. Perhaps a cronjob that restarts the docker daemon?

Hi, and thanks.
Yes indeed, but it was kind of difficult to figure it out since I have a scheduled backup task that stops the container, and brings them back on, but it needs to be changed to contain the names of active ones. I forgot to put this one.
Replying now because I forgot it and now that I'm searching for an issue I saw this one.

Sorry for the delay, and thanks again for the reply.
Regards.
JG
