### ISSUE TITLE
DB-Migration not working

### ISSUE THREAD

**Issue by schnillerman** [opf/openproject-docker-compose#54]
Coming from working container of openproject image 11, switching to 12 (also working with deprecated db warning) and trying to apply [db migration](https://www.openproject.org/docs/installation-and-operations/misc/migration-to-postgresql13/#all-in-one-docker-installation), the following error comes up:
![image](https://github.com/opf/openproject-deploy/assets/17252473/832834ea-9565-4eaf-8e87-0cb4134a6f79)

**Comment by openpkrump** [comment]
Hi schnillerman, thank you for reaching out to us. Inquiries like these one are handled within our helpdesk system. If you have issues like these and have an enterprise plan, please email us (mailto:support@openproject.com)
