### ISSUE TITLE
Invalid interpolation format error in compose

### ISSUE THREAD

**Issue by abhijith2109** [opf/openproject-docker-compose#58]
ERROR: Invalid interpolation format for "environment" option in service "web": "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"

Trying to deploy openproject using docker-compose i am getting the above error.

**Comment by openpkrump** [comment]
Hi abhijith2109, thank you for reaching out to us. Inquiries like these one are handled within our helpdesk system. If you have issues like these and have an enterprise plan, please email us (mailto:support@openproject.com)
