### ISSUE TITLE
Upgrading from 12 to 13 with external Postgres DB v15

### ISSUE THREAD

**Issue by jasgggit** [opf/openproject-docker-compose#60]
Hi, I'm trying to upgrade from the 12 to 13 version, using docker compose deployment.
I do:

docker-compose down
Edit the TAG in my docker-copse.yml file to 13:
:  image: openproject/community:${TAG:-13}

do:
docker-compose pull

and them:
 docker-compose up -d

But my 'web' container doesn't stay UP saying the below log:

How can I execute the upgrade manually? since the docs only show the steps for the container version, and also I cannot use the 'web' container console since doesn't stay up enough for that.

Hope someone has some ideas.

Thanks and regards.
JG
------// 
=> Booting Puma
=> Rails 7.0.7 application starting in production 
=> Run `bin/rails server --help` for more startup options

Exiting

/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.7/lib/active_record/migration.rb:627:in `check_pending!':  (ActiveRecord::PendingMigrationError)

Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate RAILS_ENV=production

You have 21 pending migrations:

20230314165213_add_foreign_keys_to_work_packages.rb
20230315103437_add_foreign_keys_to_workflows.rb
20230315183431_add_foreign_keys_to_projects_types.rb
20230315184533_add_foreign_keys_to_custom_fields_projects.rb
20230322135932_merge_wiki_content_into_page.rb
20230328154645_add_gin_trgm_index_on_journals_and_custom_values.rb
20230508150835_copy_project_status_into_projects_and_journals.rb
20230531093004_remove_default_from_query_name.rb
20230606083221_add_cause_to_journal.rb
20230608151123_add_validity_period_to_journals.rb
20230613155001_add_export_logo_to_custom_style.rb
20230713144232_create_storages_file_link_journals.rb
20230717104700_drop_export_card_configurations.rb
20230718084649_add_create_user_permission_to_roles.rb
20230725165505_add_storage_name_to_storages_file_links_journals.rb
20230726061920_rename_auth_source_to_ldap_auth_source.rb
20230726112130_remove_type_from_ldap_auth_sources.rb
20230731153909_add_file_link_journals_to_existing_containers.rb
20230803113215_add_indices_to_work_package_journals.rb
20230808080001_remove_some_string_length_constraints.rb
20230808140921_add_derived_remaining_hours_to_work_packages.rb

	from /app/config/initializers/06-pending_migrations_check.rb:34:in `<top (required)>'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.7/lib/rails/engine.rb:667:in `load'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.7/lib/rails/engine.rb:667:in `block in load_config_initializer'
	from /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.7/lib/active_support/notifications.rb:208:in `instrument'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.7/lib/rails/engine.rb:666:in `load_config_initializer'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.7/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.7/lib/rails/engine.rb:619:in `each'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.7/lib/rails/engine.rb:619:in `block in <class:Engine>'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.7/lib/rails/initializable.rb:32:in `instance_exec'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.7/lib/rails/initializable.rb:32:in `run'
..///...

**Comment by openpkrump** [comment]
Hi jasgggit, thank you for reaching out to us. Inquiries like these one are handled within our helpdesk system. If you have issues like these and have an enterprise plan, please email us (mailto:support@openproject.com)
