### ISSUE TITLE
Can not upgrade from 12 to 13

### ISSUE THREAD

**Issue by SFKS** [opf/openproject-docker-compose#61]
I am following this steps: https://github.com/opf/openproject-deploy/tree/stable/13/compose/control#upgrade

(Ubuntu 20.04.6 LTS)

If I stay in OpenProject 12 the postgres upgrade from 10 to 13 works.

But when upgrading to OpenProject 13 compose_web_1 goes into a kind of crash loop:

`-----> Setting PGVERSION=13 PGBIN=/usr/lib/postgresql/13/bin PGCONF_FILE=/etc/postgresql/13/main/postgresql.conf`
` => Booting Puma`
`=> Rails 7.0.7 application starting in production`
`=> Run bin/rails server --help for more startup options`

Am I missing something?
Any help woluld be apreciated.

**Comment by openpkrump** [comment]
Hi SFKS, thank you for reaching out to us. Inquiries like these one are handled within our helpdesk system. If you have issues like these and have an enterprise plan, please send us an email to support@openproject.com
