### ISSUE TITLE
Large size after installation

### ISSUE THREAD

**Issue by SequelONE** [opf/openproject-docker-compose#63]
I have a problem. After installation with docker-compose, if you go to the panel itself -> Administration -> Information, it shows that openproject takes up 65GB of disk space. Compared with the version installed on the server, with attachment files the system takes up 3GB of space. How to configure docker to reduce size?

**Comment by tiroessler** [comment]
The storage numbers shown under Administration -> Information shows the storage used on your hard drive, not how much storage is used by OpenProject.
So for example if on your hard drive 200 GB are used then it shows that no matter if this data is used from OpenProject or other files and applications.
