### ISSUE TITLE
docker-compose.yml still referencing old docker image.

### ISSUE THREAD

**Issue by marklowski** [opf/openproject-docker-compose#65]
Hi, i just had an error when i tried pull via docker-compose.

Then i checked  the corresponding file and found that within the docker-compose.yml the image still references to the old docker Image **"openproject/community"**. Apparently the Docker Image was renamed to  **"openproject/openproject"**, that's at least mentioned on DockerHub within the Old Image. After Changing the Docker Image to **"openproject/openproject"** the pull worked as expected.

Could you please look into the Issue?
Thank you.

- Old DockerHub Image [openproject/community](https://hub.docker.com/r/openproject/community/#!)
- New? DockerHub Image [openproject/openproject](https://hub.docker.com/r/openproject/openproject)

**Comment by tbaden** [comment]
I can confirm the issue. It's also listed here: https://www.openproject.org/docs/release-notes/14-0-0/ to use openproject/openproject
