### ISSUE TITLE
Instruction error - docker-compose should be docker compose

### ISSUE THREAD

**Issue by snesbittsea** [opf/openproject-docker-compose#68]
Instructions indicate one should use the `docker-compose` command. Doing so will result in following exception:
`docker.errors.DockerException: Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked' `

I was able to get it to work with the `docker compose` command

**Comment by oliverguenther** [comment]
Fixed in https://github.com/opf/openproject-docker-compose/tree/dev , will be published to `stable/14` next week as part of the 14.5.0 release
