### ISSUE TITLE
How do I deploy OpenProject on Kubernetes?

### ISSUE THREAD

**Issue by adrianovieira** [opf/openproject-docker-compose#7]
hey, guys!
I heard from OpenProject a few weeks ago!
Then the company I work for ([Empresa Brasil de Comunicação - EBC](https://www.ebc.com.br)) requested our IT team a deployment to test it out.

Since then, I have been working in its deployment on Kubernetes.
The work have done with it so far is good enough to deploy an staging environment.
So here we are, I made the project available on Gitlab.com at:
https://gitlab.com/adrianovieira/openproject.org-helm-chart

Please, stop by to analyse it. 🙏🏾
And if you want to help with something or even have any comments let us know, please.

Regards.

*Go OpenProject go*.

**Comment by airmonitor** [comment]
Hey @adrianovieira.

Many thx for your work!

From my side I've reconfigured little apache config to allow listening on port 443.

This allowed me to easily use ingress with https backend

Also I bumped container version to 12.0.4


`
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-cm
data:
  openproject.conf: |
    <VirtualHost *:80>
      ServerName _default_
      DocumentRoot /app/public

      ProxyRequests off
      ProxyPreserveHost On


      <Location />
        ProxyPass http://127.0.0.1:8080/ retry=0
        ProxyPassReverse http://127.0.0.1:8080/
      </Location>
    </VirtualHost>


    <VirtualHost *:443>
        SSLEngine On
        SSLCertificateFile      /etc/ssl/certs/ssl-cert-snakeoil.pem
        SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key

        RequestHeader set X-Forwarded-Proto "https"

        ServerName _default_
        DocumentRoot /app/public

        ProxyRequests off
        <Location />
            ProxyPass http://127.0.0.1:8080/ retry=0
            ProxyPassReverse http://127.0.0.1:8080/
        </Location>


     </VirtualHost>

    <IfModule mod_ssl.c>
        SSLStaplingCache shmcb:/var/run/apache2/stapling_cache(128000)
    </IfModule>
`

**Comment by machisuji** [comment]
I'm sorry we didn't reply to this. Thanks for sharing your work. In the meantime we had developed our own helm charts independently: https://charts.openproject.org/

But perhaps we can learn something from what you've build. Ideally you wouldn't need to maintain your own version.
Please feel free to check out our helm charts too and let us know if you find any issues that would prevent you from using them.

I'll close this issue, but feel to open a new one in that case.
