### ISSUE TITLE
Export feature doesn't work (missing volume)

### ISSUE THREAD

**Issue by CallMeLaNN** [opf/openproject-docker-compose#71]
Since this is a stable/14 release from the main branch, I have to inform that all Export feature doesn't work.

After spending a day, I discovered the [`volumes` added here](https://github.com/opf/openproject-deploy/pull/70/files#diff-6279b4379956d40a7c808ee22b5f1005cb7d1f6bfa77d45adc2e004f7ef3e6f9R85) from #70  causes the `volumes` defined in the `x-op-app` to be replaced.

This can be confirmed with `docker compose config`. I struggled to understand the merging until I realized that the issue was not with compose merging, but with the yaml merge key `<<:`. This key causes the `volumes` from the current `web` mapping replace the `volumes` from `x-op-app`, rather than merging them.

As a result, `"${OPDATA:-opdata}:/var/openproject/assets"` is missing from `web` service. I hope this will help to fix and help anyone to try-out this using the latest docker compose.

I managed to get the export working by adding the missing volume directly to `web` in my compose override.

```yaml
...
services:
  ...
  web:
    volumes:
      - "${OPDATA:-opdata}:/var/openproject/assets" # Add this
      - assets:/app/public
```

BTW, it's great to have Caddy, but I would like to modify the template since everything is already in the stack. Consider using `lucaslorentz/caddy-docker-proxy` for dynamic Caddyfile which I managed to replace the proxy service to that.

**Comment by estan** [comment]
Maybe @Kharonus or @machisuji know what would be the proper fix of this, so we don't have to add workaround above?

**Comment by Kharonus** [comment]
Thanks a ton for doing the first research already, @CallMeLaNN ! Indeed, the yaml anchors do not support merging of list values. Hence, as we wanted to add a specific volume to the `web` service, we now have to extract the volumes from the `x-op-app` anchor and define them on the services directly.

This way you should be able to remove the lines from your `docker-compose.override.yml` again.
