### ISSUE TITLE
exec /usr/local/bin/proxy-entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by michaelhugj** [opf/openproject-docker-compose#72]
Hello Expert,
We I installed the OP compose in Dorcker for windows, and started it.
compose-proxy-1 always have an error exec /usr/local/bin/proxy-entrypoint.sh: no such file or directory.
![Error](https://github.com/opf/openproject-deploy/assets/170851952/8f10074e-0a9e-4b3a-97f2-32a3f23f9b62)
But the file could be found in the installation folder.

The current docker is Docker Desktop 4.30.0 (149282), and the OP Compose is latest version 4.1.
How to fix this, Please help .
Regards,
Mic

**Comment by michaelhugj** [comment]
I re-downloaded this file from https://github.com/opf/openproject-deploy/blob/stable/14/compose/proxy-entrypoint.sh,
the service could be executed successfully. But I couldn't login with the default username and password ( login: admin, and password: admin.).

**Comment by comounburro** [comment]
same issue on windows. the file is identical to what is on github. still have issues. 

```
proxy-1     | exec /usr/local/bin/proxy-entrypoint.sh: no such file or directory
```

**Comment by comounburro** [comment]
> same issue on windows. the file is identical to what is on github. still have issues.
> 
> ```
> proxy-1     | exec /usr/local/bin/proxy-entrypoint.sh: no such file or directory
> ```

due to windows git (I think) it gets the files with CRLF instead of LF. saved the important files as LF format and the project runs.
I can't login with admin:admin. error:
![image](https://github.com/opf/openproject-deploy/assets/35922430/f64e4988-8019-4223-929b-eb282097b57d)

**Comment by habib-e** [comment]
same issue on windows.

**Comment by oliverguenther** [comment]
We're now using a separate proxy image that is built without this entrypoint file. Is the problem still relevant?
