### ISSUE TITLE
Compose: First login on fresh install fails due to wrong file permissions in mounted assets folder.

### ISSUE THREAD

**Issue by CybotTM** [opf/openproject-docker-compose#77]
First login after starting the composer stack fails with:

"Invalid user or password or the account is blocked due to multiple failed login attempts. If so, it will be unblocked automatically in a short time."

Due to wrong permissions in mounted volumes:

```
seeder-1    |  ↳ OverviewSeeder
seeder-1    | *** Seeding Overview
seeder-1    |    -Creating overview for Demo project
seeder-1    | rake aborted!
seeder-1    | Errno::EACCES: Permission denied @ dir_s_mkdir - /var/openproject/assets/files (Errno::EACCES)
seeder-1    | /app/lib/open_project/patches/fog_file.rb:12:in `mkdir!'
```

This error is hard to catch, maybe it should be more prominent or prevent successful container starting at all.
Or it should be mentioned in the documentation how to create this folder.

**Comment by twkrol** [comment]
Is there any workaround?

my dirty solution is:
```shell

docker exec -u root -it compose_web_1 chmod a+rwx /var/openproject -R

**Comment by itnavigate** [comment]
Definitely as show stopper for new users.  

For the Copy-n-Paste trouble shooters, 
My solution based on @twkrol is 
```
docker exec -u root -it compose-web-1 chmod a+rwx /var/openproject -R
```
I had to replace the underscores with dashes

**Comment by zhongsdjn** [comment]
I had the same problem!After finish installing, It`s wrong,Can`t login, I think it is  a serious problems for this project!Do they publish without verifying it often?

**Comment by tiroessler** [comment]
Seams to be the same issue as #80
