### ISSUE TITLE
An error occurred while sending mail (Net::ReadTimeout with #<TCPSocket:(closed)>)

### ISSUE THREAD

**Issue by zhongsdjn** [opf/openproject-docker-compose#84]
OS: Ubuntu22/CentOS Stream9 vmware
Version:14-slim
Method: docker compose

Everything is fine at my cloud server! However, the same configuration cannot send mails locally host,Ports are open, firewalls are closed! And the following configuration is also such a problem!
worker:
   dns:    
     - 8.8.8.8
     - "Your DNS IP"

**Comment by oliverguenther** [comment]
This is not a problem of the docker compose setup, but your container is not able to connect to your SMTP server

**Comment by zhongsdjn** [comment]
No! The main problem is not smtp!It's the authentication mode! Sometimes use account and password,sometimes need use token, not sure why!




| |
zhongsdjn
|
|
***@***.***
|
---- Replied Message ----
| From | Oliver ***@***.***> |
| Date | 9/2/2024 14:34 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [opf/openproject-deploy] An error occurred while sending mail (Net::ReadTimeout with #<TCPSocket:(closed)>) (Issue #84) |

This is not a problem of the docker compose setup, but your container is not able to connect to your SMTP server

**Comment by oliverguenther** [comment]
If you get a Net::ReadTimeout, your SMTP server doesn't answer in time. This is unrelated to the authentication mode.

**Comment by zhongsdjn** [comment]
All right!  All I can say is I'm sure! And will not return to the question


| |
zhongsdjn
|
|
***@***.***
|
---- Replied Message ----
| From | Oliver ***@***.***> |
| Date | 9/2/2024 14:39 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [opf/openproject-deploy] An error occurred while sending mail (Net::ReadTimeout with #<TCPSocket:(closed)>) (Issue #84) |

If you get a Net::ReadTimeout, your SMTP server doesn't answer in time. This is unrelated to the authentication mode.
