### ISSUE TITLE
openproject/proxy  repository does not exist

### ISSUE THREAD

**Issue by zhongsdjn** [opf/openproject-docker-compose#85]
! proxy Warning                                         pull access denied for openproject/proxy, repository does not exist or may re...               28.6s
 ✔ web Pulled                                                                                                                                           17.7s
WARNING: Some service image(s) must be built from source by running:
    docker compose build proxy
1 error occurred:
        * Error response from daemon: pull access denied for openproject/proxy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by massimiliano-dalcero** [comment]
Hello
I have same errore.
When running "docker compose pull" obtain this error/warning:

`! proxy Warning    pull access denied for openproject/proxy, repository does not exist or may require 'docker login': denied: requested access to the resource is denid`

```
WARNING: Some service image(s) must be built from source by running:
    docker compose build proxy
1 error occurred:
        * Error response from daemon: pull access denied for openproject/proxy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by lemiliomoreno** [comment]
Seems like the issue is with this commit https://github.com/opf/openproject-deploy/commit/6b10106a0fe300af7523ff80bd4f3abb95bc4bc5 - https://github.com/opf/openproject-deploy/pull/83, openproject/proxy image is not available in docker hub so it's not able to download it.

If you are trying to run a dev environment to test the tool, try the [all-in-one container](https://www.openproject.org/docs/installation-and-operations/installation/docker/#all-in-one-container).

**Comment by FlipperPlz** [comment]
Will this ever be fixed? How can I install this for production?

**Comment by zhongsdjn** [comment]
> Will this ever be fixed? How can I install this for production?
@FlipperPlz 
No! A lot of problems, developers don't seem to care about user feedback!Many problems have not been fixed so far

**Comment by sseide** [comment]
Same problem after update OpenProject update after new release notes for 14.4.2 - `pull access denied`

Also someone at the forum with this problem without response util now:
https://community.openproject.org/topics/18888

@lindenthal @wielinde @birthe @oliverguenther 
Would be nice if someone from OpenProject either fixes Docker access rights or updates installation instructions!
Currently NOT POSSIBLE to setup new systems´ (or update existing ones)

**Comment by patric0889** [comment]
Sadly, OpenProject is broken for production, strange concept of "stable" tho

**Comment by oliverguenther** [comment]
You probably have an older compose version that doesn't allow specifying both build: and image: properties. Could you comment the compose version you're using? 

Could you try removing the image: openproject/proxy definition as shown in https://github.com/opf/openproject-deploy/issues/88

You may have to run _docker compose build proxy_

**Comment by Kharonus** [comment]
If you want to update your stack when there is a service with a local build context, run `docker compose build --pull`.

**Comment by sseide** [comment]
i am using current "stable/14" branch. Which - according to its name - is the current one to use for the current OpenProject 14.x. And i started it with simple "docker compose up", no build before. So its just trying to fetch the image.

And for my self  i did get it up and running this weekend with two other changes:
- completly removed "proxy" service
- added "ports" declaration to the "web" service.

As i have another reverse proxy in front of it myself (NGinx) i do know know what the proxy image is needed for. Seems to be duplicate in this specific case.

**Comment by sseide** [comment]
If there is an compose build needed please update the `compose/README.md` file to show all steps necessary. Current state does not mention it at all.

**Comment by Kharonus** [comment]
> As i have another reverse proxy in front of it myself (NGinx) i do know know what the proxy image is needed for. Seems to be duplicate in this specific case.

As the deploy repository was updated to work standalone and on the `slim` image tag, a proxy is needed to access the backend application service. Before the update for `slim`, the in-built proxy of the `openproject` image was used. But this is not included in `slim`.

The solution was to use a lightweight proxy service, built locally. As always, one must adapt this stack to the real needs of ones setup. So, removing/replacing the proxy is one feasible solution. Adding redirection rules and comparable stuff, is another.

> If there is an compose build needed please update the `compose/README.md` file to show all steps necessary. Current state does not mention it at all.

This will be done in the linked PR #88. You can enter the discussion there, too, if you want. ;) We try to keep those decisions transparent.

**Comment by sseide** [comment]
And somehow related - the README inside the `compose/control/` directory mentions something about being the `stable/12` branch, uses `docker-compose` and stuff. Is this current or needs an Update too?

**Comment by Kharonus** [comment]
I take `compose/control/README.md` into discussion. Let see, if this one survives in future, of if this knowledge is covered by the README of the parent. Thanks for pointing it out, this one is definitely far behind. ^^
