### ISSUE TITLE
[Error 403] You do not have access to this page.

### ISSUE THREAD

**Issue by zhongsdjn** [opf/openproject-docker-compose#86]
[Error 403] You do not have access to this page.
[错误 403] 您无权访问此页。

As Admin，That can't access /activity! 
And,so many problem，Don't you guys validate the version before you release it？You never address a problem after it's raised？

**Comment by oliverguenther** [comment]
Please provide additional information on your installation, such as logs and installed version

**Comment by oliverguenther** [comment]
I assume you're affected by this bug, and get a 403 if there is no visible project in your instance. https://community.openproject.org/projects/openproject/work_packages/57585/activity

It will be fixed as 14.5.0.
