### ISSUE TITLE
Missing docker-compose.override.yml.

### ISSUE THREAD

**Issue by R1D3R175** [opf/openproject-docker-compose#89]
As title says, file is missing. 

According to [this page](https://www.openproject.org/docs/installation-and-operations/configuration/), it should be there

**Comment by oliverguenther** [comment]
Thanks for your report! You simply create this file and docker compose will pick it up (see https://docs.docker.com/compose/multiple-compose-files/merge/ for more information). I've extended the documentation to make this a bit clearer.
