### ISSUE TITLE
instructions not working for Upgrade with control plane

### ISSUE THREAD

**Issue by sseide** [opf/openproject-docker-compose#94]
Hello,

after your update of the README it says in the "Upgrade section:
https://github.com/opf/openproject-docker-compose/blob/abc05eab971a32faaaa0bf35efd3f70e68d54738/README.md?plain=1#L114-L116

This command is failing because the control.yml file has the old `service: ` line at the top:
```
ERROR: Version mismatch: file ./docker-compose.yml specifies version 1 but extension file ./docker-compose.control.yml uses version 3.7
```
And all commands are `docker-compose` instead of new `docker compose`.

p.s. the Link to the "Docker compose installation guide" in the OpenProject 14.5.0 release email is wrong - it points to a non-existant githubusercontent url.

**Comment by tiroessler** [comment]
The control plane should work now since we fixed #97 today.
Please make sure you have pulled the newest files in your local copy git repo.
