### ISSUE TITLE
Question: Difference between docker image :14 and :14-slim?

### ISSUE THREAD

**Issue by sseide** [opf/openproject-docker-compose#95]
Since some time an new image "14-slim" exists. But docker installation instruction does not mention the differnces between the normal and the slim images. Only place the "slim" image is mentioned building own plugins.

Please update documentation to list differences between booth images to allow an informed selection of either one or the other.

Places searched:
- https://hub.docker.com/r/openproject/openproject
- https://www.openproject.org/docs/installation-and-operations/installation/docker/ (=> here reference to plugin usage)
- https://github.com/opf/openproject-docker-compose

**Comment by openpkrump** [comment]
Hi sseide,
thank you for sharing this input with us. I created a request for the team for this.
You can follow it here: https://community.openproject.org/projects/openproject/work_packages/details/58348/overview

**Comment by sseide** [comment]
seen its there now - thanks:

https://www.openproject.org/docs/installation-and-operations/installation/docker/#available-containers
https://github.com/opf/openproject-docker-compose/blob/stable/14/README.md
