### ISSUE TITLE
Changing PORT using .env file does not work and makes the web container exit.

### ISSUE THREAD

**Issue by asdfsnlr** [opf/openproject-docker-compose#96]
As the title suggests, changing the port configuration with the .env  file makes the web container fail and enter a permanet staring cycle.

port config in .env file:
![image](https://github.com/user-attachments/assets/41feeda9-7b5b-4e1f-bc42-d8045e810778)

Web Container log:
![image](https://github.com/user-attachments/assets/872e5bda-62ee-41b0-9a35-b1161c1bbea6)

**Comment by openpkrump** [comment]
Hi asdfsnlr,
please try only '4000' as PORT without the IP Adress. Make sure to edit the hostname aswell

**Comment by asdfsnlr** [comment]
Hi openpkrump.
Thanks for the response. Eventually worked that out sorry for waisting your time.
Cheers!!
